version: "3"
services:
  micolmenaback:
    build: ./back
    ports:
      - "2222:2222"
    environment:
      DB_HOST: host.docker.internal
      DB_USER: erikaastef99
  micolmenafront:
    build: ./front
    ports:
      - "80:3000"
  db:
    container_name: "psql"
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: miColmena
      POSTGRES_USER: erikaastef99
