import { types } from "mobx-state-tree";

const ConsejosForms = types.model("Consejos", {
  abejasAgregadas: types.maybeNull(types.boolean),
  acarapisosis: types.maybeNull(types.boolean),
  agregarAbejas: types.maybeNull(types.boolean),
  agregarReina: types.maybeNull(types.boolean),
  antibioticos: types.maybeNull(types.boolean),
  antihongos: types.maybeNull(types.boolean),
  antivarroa: types.maybeNull(types.boolean),
  celdasCambiadas: types.maybeNull(types.boolean),
  cera: types.maybeNull(types.string),
  colmenaAislante: types.maybeNull(types.boolean),
  colmenaDividida: types.maybeNull(types.boolean),
  colmenaLimpia: types.maybeNull(types.boolean),
  exclusorReina: types.maybeNull(types.boolean),
  exclusorReina2: types.maybeNull(types.boolean),
  exclusorReina3: types.maybeNull(types.boolean),
  jaleaReal: types.maybeNull(types.string),
  jarabeEspeso: types.maybeNull(types.boolean),
  jarabeLiviano: types.maybeNull(types.boolean),
  medEscara: types.maybeNull(types.boolean),
  medNosema: types.maybeNull(types.boolean),
  mezclaSeca: types.maybeNull(types.boolean),
  miel: types.maybeNull(types.string),
  nosema: types.maybeNull(types.boolean),
  nuevaColmenaAlimentos: types.maybeNull(types.boolean),
  nuevaColmenaIntervenciones: types.maybeNull(types.boolean),
  otrosAntivarroa: types.maybeNull(types.boolean),
  panal: types.maybeNull(types.string),
  pantallaAbierta: types.maybeNull(types.boolean),
  pantallaCerrada: types.maybeNull(types.boolean),
  polen: types.maybeNull(types.string),
  propoleo: types.maybeNull(types.string),
  reinaAgregada: types.maybeNull(types.boolean),
  unidadCera: types.maybeNull(types.string),
  unidadJaleaReal: types.maybeNull(types.string),
  unidadMiel: types.maybeNull(types.string),
  unidadPanal: types.maybeNull(types.string),
  unidadPolen: types.maybeNull(types.string),
  unidadPropoleo: types.maybeNull(types.string),
});

export default ConsejosForms;
